[project]
name = "django-miniproject-todo-list"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.2",
    "django-stubs>=5.2.0",
    "mypy>=1.16.0",
    "ruff>=0.11.13",
]
